import type { DatasetSummary, EvidenceProvenance, RankedDrugHypothesis, RankedMutationRecord } from "./types";
import { researchUseDisclaimer } from "./content";

export function buildReportMarkdown(input: {
  summary: DatasetSummary;
  mutations: RankedMutationRecord[];
  drugHypotheses: RankedDrugHypothesis[];
  evidenceProvenance: EvidenceProvenance[];
  validationSteps: string[];
}): string {
  const { summary, mutations, drugHypotheses, evidenceProvenance, validationSteps } = input;
  const lines: string[] = [];
  lines.push(`# OncoQ.tech Research Brief`);
  lines.push("");
  lines.push(`**Cohort:** ${summary.cohort.name}`);
  lines.push(`**Cancer type:** ${summary.cohort.cancerType}`);
  lines.push(`**Samples:** ${summary.cohort.sampleCount}`);
  lines.push(`**Mutation signals:** ${summary.mutationCount}`);
  lines.push(`**Genes detected:** ${summary.genesDetected.join(", ")}`);
  lines.push(`**Generated:** ${new Date().toISOString().slice(0, 10)}`);
  lines.push("");
  lines.push(`> ${researchUseDisclaimer}`);
  lines.push("");
  lines.push(`## Mutation relevance ranking`);
  lines.push("");
  lines.push(`| Rank | Gene | Variant | Pathway | Evidence | Score |`);
  lines.push(`| --- | --- | --- | --- | --- | --- |`);
  mutations.forEach((mutation, index) => {
    lines.push(`| ${index + 1} | ${mutation.gene} | ${mutation.variant} | ${mutation.pathway} | ${mutation.evidenceCategory} | ${mutation.prototypeRelevanceScore} |`);
  });
  lines.push("");
  lines.push(`## Drug-repurposing hypothesis shortlist`);
  lines.push("");
  drugHypotheses.forEach((drug, index) => {
    lines.push(`### ${index + 1}. ${drug.candidateClass} — priority ${drug.compositePriorityScore}`);
    lines.push("");
    lines.push(`- Target: ${drug.target}`);
    lines.push(`- Matched signal: ${drug.matchedMutationSignal}`);
    lines.push(`- Evidence: ${drug.evidenceCategory}`);
    lines.push(`- Why ranked: ${drug.whyRanked}`);
    lines.push(`- Limitation: ${drug.limitation}`);
    lines.push(`- Next validation: ${drug.nextValidationStep}`);
    lines.push("");
  });
  lines.push(`## Evidence provenance`);
  lines.push("");
  lines.push(`| Layer | Phase 2 source | Future plan | Limitation |`);
  lines.push(`| --- | --- | --- | --- |`);
  evidenceProvenance.forEach((item) => {
    lines.push(`| ${item.evidenceLayer} | ${item.phase2Source} | ${item.futureSourcePlan} | ${item.limitation} |`);
  });
  lines.push("");
  lines.push(`## Recommended validation steps`);
  lines.push("");
  validationSteps.forEach((step, index) => {
    lines.push(`${index + 1}. ${step}`);
  });
  lines.push("");
  lines.push(`---`);
  lines.push(`Generated by OncoQ.tech prototype — research-use only.`);
  return lines.join("\n");
}

export function buildReportSummary(input: {
  summary: DatasetSummary;
  drugHypotheses: RankedDrugHypothesis[];
}): string {
  const { summary, drugHypotheses } = input;
  const topThree = drugHypotheses.slice(0, 3).map((drug, index) => `${index + 1}. ${drug.candidateClass} (priority ${drug.compositePriorityScore}, ${drug.evidenceCategory})`).join("\n");
  return [
    `OncoQ.tech research brief — ${summary.cohort.name}`,
    `Samples: ${summary.cohort.sampleCount} | Mutation signals: ${summary.mutationCount}`,
    `Genes: ${summary.genesDetected.join(", ")}`,
    "",
    `Top candidate classes:`,
    topThree,
    "",
    researchUseDisclaimer
  ].join("\n");
}

export function buildPilotSow(input: {
  customer: string;
  cohortName: string;
  analystRate: number;
  hoursSaved: number;
}): string {
  const value = Math.round(input.analystRate * input.hoursSaved);
  return [
    `# OncoQ.tech — Paid Research Pilot Statement of Work (Draft)`,
    ``,
    `**Customer:** ${input.customer}`,
    `**Cohort:** ${input.cohortName}`,
    `**Pilot fee:** RM50,000 fixed`,
    `**Duration:** 3 months`,
    `**Generated:** ${new Date().toISOString().slice(0, 10)}`,
    ``,
    `## Pilot scope`,
    `1. Secure de-identified cohort intake and schema review.`,
    `2. Mutation relevance ranking on the customer cohort.`,
    `3. Drug-repurposing hypothesis shortlist with evidence provenance.`,
    `4. Expert-review workshop (bioinformatics + oncology research + pathology).`,
    `5. Retrospective benchmark plan against curated knowledgebases.`,
    `6. Final research brief, limitations log, and validation roadmap.`,
    ``,
    `## Estimated workflow value`,
    `- Analyst hours saved (estimated): ${input.hoursSaved}`,
    `- Internal value at RM${input.analystRate}/hr: ~RM${value.toLocaleString()}`,
    `- Time-to-shortlist target: research-grade in days, not weeks.`,
    ``,
    `## Draft pilot terms`,
    `- Pilot fee: RM50,000, payable 50% on signing, 50% on delivery.`,
    `- Research workspace conversion option: RM120,000 / year for one team workspace.`,
    `- Enterprise research licence range: RM250,000 - RM500,000 / year, subject to scope.`,
    ``,
    `## Guardrails`,
    `- ${researchUseDisclaimer}`,
    `- All outputs are ranked investigation hypotheses for expert review.`,
    `- De-identified data only. No personal identifiers accepted.`,
    ``,
    `---`,
    `Draft SOW generated by OncoQ.tech prototype. Final terms subject to mutual agreement.`
  ].join("\n");
}

export function downloadTextFile(content: string, filename: string, mime: string = "text/markdown") {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1500);
}

export async function copyToClipboard(text: string): Promise<boolean> {
  if (typeof navigator === "undefined" || !navigator.clipboard) return false;
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}
